from django.db import models

# Create your models here.
class responden(models.Model):
	id = models.BigAutoField(primary_key=True)
	name = models.CharField(max_length=200)
	gender = models.CharField(max_length=200)
	age = models.IntegerField()
	prov = models.CharField(max_length=200)
	kab = models.CharField(max_length=200)
	statusnikah = models.CharField(max_length=50)
	jumlahanak = models.CharField(max_length=5)
	usiaanak1 = models.CharField(max_length=5)
	usiaanak2 = models.CharField(max_length=5)
	educ = models.CharField(max_length=200)
	job = models.CharField(max_length=200)
	nohp = models.CharField(max_length=20)
	date = models.DateTimeField(auto_now_add=True)

	def __str__(self):
		return self.name

class wilayah(models.Model):
	kode_kab = models.IntegerField()
	kode_prov = models.IntegerField()
	kabupaten = models.CharField(max_length=200)
	provinsi = models.CharField(max_length=200)

class question(models.Model):
	questionID = models.IntegerField()
	question = models.TextField()
	category = models.CharField(max_length=200)
	option1 = models.TextField()
	option2 = models.TextField()
	option3 = models.TextField()
	option4 = models.TextField()
	paralel = models.CharField(max_length=200)

class sessionScore(models.Model):
	id = models.BigAutoField(primary_key=True)
	quest1Scr = models.IntegerField()
	quest2Scr = models.IntegerField()
	quest3Scr = models.IntegerField()
	quest4Scr = models.IntegerField()
	quest5Scr = models.IntegerField()
	quest6Scr = models.IntegerField()
	quest7Scr = models.IntegerField()
	quest8Scr = models.IntegerField()
	quest9Scr = models.IntegerField()
	quest10Scr = models.IntegerField()
	quest11Scr = models.IntegerField()
	quest12Scr = models.IntegerField()
	quest13Scr = models.IntegerField()
	quest14Scr = models.IntegerField()
	quest15Scr = models.IntegerField()
	quest16Scr = models.IntegerField()
	quest17Scr = models.IntegerField()
	quest18Scr = models.IntegerField()
	quest19Scr = models.IntegerField()
	quest20Scr = models.IntegerField()
	quest21Scr = models.IntegerField()
	quest22Scr = models.IntegerField()
	quest23Scr = models.IntegerField()
	quest24Scr = models.IntegerField()
	quest25Scr = models.IntegerField()
	quest26Scr = models.IntegerField()
	quest27Scr = models.IntegerField()
	quest28Scr = models.IntegerField()
	quest29Scr = models.IntegerField()
	quest30Scr = models.IntegerField()
	quest31Scr = models.IntegerField()
	quest32Scr = models.IntegerField()
	quest33Scr = models.IntegerField()
	quest34Scr = models.IntegerField()
	quest35Scr = models.IntegerField()
	quest36Scr = models.IntegerField()
	quest37Scr = models.IntegerField()
	quest38Scr = models.IntegerField()
	quest39Scr = models.IntegerField()
	quest40Scr = models.IntegerField()

class sessionMark(models.Model):
	id = models.BigAutoField(primary_key=True)
	quest1Ans = models.IntegerField()
	quest2Ans = models.IntegerField()
	quest3Ans = models.IntegerField()
	quest4Ans = models.IntegerField()
	quest5Ans = models.IntegerField()
	quest6Ans = models.IntegerField()
	quest7Ans = models.IntegerField()
	quest8Ans = models.IntegerField()
	quest9Ans = models.IntegerField()
	quest10Ans = models.IntegerField()
	quest11Ans = models.IntegerField()
	quest12Ans = models.IntegerField()
	quest13Ans = models.IntegerField()
	quest14Ans = models.IntegerField()
	quest15Ans = models.IntegerField()
	quest16Ans = models.IntegerField()
	quest17Ans = models.IntegerField()
	quest18Ans = models.IntegerField()
	quest19Ans = models.IntegerField()
	quest20Ans = models.IntegerField()
	quest21Ans = models.IntegerField()
	quest22Ans = models.IntegerField()
	quest23Ans = models.IntegerField()
	quest24Ans = models.IntegerField()
	quest25Ans = models.IntegerField()
	quest26Ans = models.IntegerField()
	quest27Ans = models.IntegerField()
	quest28Ans = models.IntegerField()
	quest29Ans = models.IntegerField()
	quest30Ans = models.IntegerField()
	quest31Ans = models.IntegerField()
	quest32Ans = models.IntegerField()
	quest33Ans = models.IntegerField()
	quest34Ans = models.IntegerField()
	quest35Ans = models.IntegerField()
	quest36Ans = models.IntegerField()
	quest37Ans = models.IntegerField()
	quest38Ans = models.IntegerField()
	quest39Ans = models.IntegerField()
	quest40Ans = models.IntegerField()

class sessionOrder(models.Model):
	id = models.BigAutoField(primary_key=True)
	quest1Pos = models.IntegerField()
	quest2Pos = models.IntegerField()
	quest3Pos = models.IntegerField()
	quest4Pos = models.IntegerField()
	quest5Pos = models.IntegerField()
	quest6Pos = models.IntegerField()
	quest7Pos = models.IntegerField()
	quest8Pos = models.IntegerField()
	quest9Pos = models.IntegerField()
	quest10Pos = models.IntegerField()
	quest11Pos = models.IntegerField()
	quest12Pos = models.IntegerField()
	quest13Pos = models.IntegerField()
	quest14Pos = models.IntegerField()
	quest15Pos = models.IntegerField()
	quest16Pos = models.IntegerField()
	quest17Pos = models.IntegerField()
	quest18Pos = models.IntegerField()
	quest19Pos = models.IntegerField()
	quest20Pos = models.IntegerField()
	quest21Pos = models.IntegerField()
	quest22Pos = models.IntegerField()
	quest23Pos = models.IntegerField()
	quest24Pos = models.IntegerField()
	quest25Pos = models.IntegerField()
	quest26Pos = models.IntegerField()
	quest27Pos = models.IntegerField()
	quest28Pos = models.IntegerField()
	quest29Pos = models.IntegerField()
	quest30Pos = models.IntegerField()
	quest31Pos = models.IntegerField()
	quest32Pos = models.IntegerField()
	quest33Pos = models.IntegerField()
	quest34Pos = models.IntegerField()
	quest35Pos = models.IntegerField()
	quest36Pos = models.IntegerField()
	quest37Pos = models.IntegerField()
	quest38Pos = models.IntegerField()
	quest39Pos = models.IntegerField()
	quest40Pos = models.IntegerField()

class session(models.Model):
	id = models.BigAutoField(primary_key=True)
	responden = models.ForeignKey(responden, on_delete=models.CASCADE)
	kognitifScore = models.IntegerField()
	sosioScore = models.IntegerField()
	fisikScore = models.IntegerField()
	totalScore = models.IntegerField()
	timeStart = models.DateTimeField(auto_now_add=False)
	timeEnd = models.DateTimeField(auto_now_add=False)
	duration = models.IntegerField()
	mark = models.ForeignKey(sessionMark, on_delete=models.CASCADE)
	order = models.ForeignKey(sessionOrder, on_delete=models.CASCADE)
	score = models.ForeignKey(sessionScore, on_delete=models.CASCADE)
	
class comment(models.Model):
	id = models.BigAutoField(primary_key=True)
	date = models.DateTimeField(auto_now_add=True)
	nama = models.CharField(max_length=200)
	comment = models.CharField(max_length=500)