# Generated by Django 3.2 on 2021-07-14 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizTest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='wilayah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_kab', models.IntegerField()),
                ('kode_prov', models.IntegerField()),
                ('kabupaten', models.CharField(max_length=200)),
                ('provinsi', models.CharField(max_length=200)),
            ],
        ),
    ]
