# Generated by Django 3.2 on 2021-07-17 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizTest', '0003_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='session',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('timeStart', models.DateTimeField()),
                ('timeEnd', models.DateTimeField()),
                ('duration', models.IntegerField()),
                ('quest1Pos', models.IntegerField()),
                ('quest2Pos', models.IntegerField()),
                ('quest3Pos', models.IntegerField()),
                ('quest4Pos', models.IntegerField()),
                ('quest5Pos', models.IntegerField()),
                ('quest6Pos', models.IntegerField()),
                ('quest7Pos', models.IntegerField()),
                ('quest8Pos', models.IntegerField()),
                ('quest9Pos', models.IntegerField()),
                ('quest10Pos', models.IntegerField()),
                ('quest11Pos', models.IntegerField()),
                ('quest12Pos', models.IntegerField()),
                ('quest13Pos', models.IntegerField()),
                ('quest14Pos', models.IntegerField()),
                ('quest15Pos', models.IntegerField()),
                ('quest16Pos', models.IntegerField()),
                ('quest1Ans', models.IntegerField()),
                ('quest2Ans', models.IntegerField()),
                ('quest3Ans', models.IntegerField()),
                ('quest4Ans', models.IntegerField()),
                ('quest5Ans', models.IntegerField()),
                ('quest6Ans', models.IntegerField()),
                ('quest7Ans', models.IntegerField()),
                ('quest8Ans', models.IntegerField()),
                ('quest9Ans', models.IntegerField()),
                ('quest10Ans', models.IntegerField()),
                ('quest11Ans', models.IntegerField()),
                ('quest12Ans', models.IntegerField()),
                ('quest13Ans', models.IntegerField()),
                ('quest14Ans', models.IntegerField()),
                ('quest15Ans', models.IntegerField()),
                ('quest16Ans', models.IntegerField()),
                ('quest1Scr', models.IntegerField()),
                ('quest2Scr', models.IntegerField()),
                ('quest3Scr', models.IntegerField()),
                ('quest4Scr', models.IntegerField()),
                ('quest5Scr', models.IntegerField()),
                ('quest6Scr', models.IntegerField()),
                ('quest7Scr', models.IntegerField()),
                ('quest8Scr', models.IntegerField()),
                ('quest9Scr', models.IntegerField()),
                ('quest10Scr', models.IntegerField()),
                ('quest11Scr', models.IntegerField()),
                ('quest12Scr', models.IntegerField()),
                ('quest13Scr', models.IntegerField()),
                ('quest14Scr', models.IntegerField()),
                ('quest15Scr', models.IntegerField()),
                ('quest16Scr', models.IntegerField()),
                ('chessScore', models.IntegerField()),
                ('mathScore', models.IntegerField()),
                ('footballScore', models.IntegerField()),
                ('geographyScore', models.IntegerField()),
                ('totalScore', models.IntegerField()),
                ('responden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizTest.responden')),
            ],
        ),
    ]
