# Generated by Django 3.2 on 2021-07-18 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizTest', '0004_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='responden',
            name='ipAddress',
            field=models.GenericIPAddressField(default='0.0.0.0'),
        ),
        migrations.AddField(
            model_name='responden',
            name='ipCity',
            field=models.CharField(default=' ', max_length=200),
        ),
        migrations.AddField(
            model_name='responden',
            name='ipCountry',
            field=models.CharField(default=' ', max_length=200),
        ),
        migrations.AddField(
            model_name='responden',
            name='ipLatitude',
            field=models.CharField(default=' ', max_length=200),
        ),
        migrations.AddField(
            model_name='responden',
            name='ipLongitude',
            field=models.CharField(default=' ', max_length=200),
        ),
        migrations.AddField(
            model_name='responden',
            name='ipOrg',
            field=models.CharField(default=' ', max_length=200),
        ),
        migrations.AddField(
            model_name='responden',
            name='ipRegion',
            field=models.CharField(default=' ', max_length=200),
        ),
        migrations.AddField(
            model_name='responden',
            name='ipTimezone',
            field=models.CharField(default=' ', max_length=200),
        ),
        migrations.AddField(
            model_name='responden',
            name='ipVersion',
            field=models.CharField(default=' ', max_length=200),
        ),
    ]
