# Generated by Django 3.2 on 2021-08-22 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizTest', '0005_auto_20210718_1623'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='responden',
            name='ipAddress',
        ),
        migrations.RemoveField(
            model_name='responden',
            name='ipCity',
        ),
        migrations.RemoveField(
            model_name='responden',
            name='ipCountry',
        ),
        migrations.RemoveField(
            model_name='responden',
            name='ipLatitude',
        ),
        migrations.RemoveField(
            model_name='responden',
            name='ipLongitude',
        ),
        migrations.RemoveField(
            model_name='responden',
            name='ipOrg',
        ),
        migrations.RemoveField(
            model_name='responden',
            name='ipRegion',
        ),
        migrations.RemoveField(
            model_name='responden',
            name='ipTimezone',
        ),
        migrations.RemoveField(
            model_name='responden',
            name='ipVersion',
        ),
        migrations.AddField(
            model_name='responden',
            name='agama',
            field=models.CharField(default='Islam', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='responden',
            name='educ',
            field=models.CharField(default='SMA', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='responden',
            name='educg',
            field=models.CharField(default='-', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='responden',
            name='gender',
            field=models.CharField(default='L', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='responden',
            name='job',
            field=models.CharField(default='-', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='responden',
            name='jobg',
            field=models.CharField(default='-', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='responden',
            name='jumlahanak',
            field=models.CharField(default='0', max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='responden',
            name='statusnikah',
            field=models.CharField(default='Belum Menikah', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='responden',
            name='usiaanak1',
            field=models.CharField(default='-', max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='responden',
            name='usiaanak2',
            field=models.CharField(default='-', max_length=5),
            preserve_default=False,
        ),
    ]
