# Generated by Django 3.2 on 2021-08-22 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizTest', '0007_auto_20210823_0122'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionmark',
            name='quest80Ans',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sessionorder',
            name='quest80Pos',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
