# Generated by Django 3.2 on 2021-09-01 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizTest', '0009_auto_20210829_2238'),
    ]

    operations = [
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('nama', models.CharField(max_length=200)),
                ('comment', models.CharField(max_length=500)),
            ],
        ),
    ]
