# Generated by Django 3.2 on 2021-11-29 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizTest', '0012_auto_20210901_2212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='chooseOption1',
        ),
        migrations.RemoveField(
            model_name='question',
            name='chooseOption2',
        ),
        migrations.RemoveField(
            model_name='question',
            name='chooseOption3',
        ),
        migrations.RemoveField(
            model_name='question',
            name='chooseOption4',
        ),
        migrations.AddField(
            model_name='question',
            name='paralel',
            field=models.CharField(default='123', max_length=200),
            preserve_default=False,
        ),
    ]
