# Generated by Django 3.2 on 2022-02-11 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizTest', '0014_auto_20220209_1804'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='responden',
            name='agama',
        ),
        migrations.RemoveField(
            model_name='responden',
            name='educg',
        ),
        migrations.RemoveField(
            model_name='responden',
            name='jobg',
        ),
    ]
